config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',            to: 'static_pages#about'
  get    '/signup',           to: 'users#new'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'
  get    '/users/:id/guides', to: 'users#guides'
  get    '/users/:id/recommendations',
                              to: 'users#recommendations'
  resources :destinations, only: %i[index show]
  resources :recommendations
  resources :users
  resources :guides, only: %i[new create show]
  resources :places, only: %i[show]
  resources :account_activations, only: %i[create edit]
  resources :password_resets, only: %i[new create edit update]
  resources :recommendations, except: %i[index]
end

app/models/recommendation.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: recommendations
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  place_id   :bigint
#  user_id    :bigint           not null
#
# Indexes
#
#  index_recommendations_on_place_id                (place_id)
#  index_recommendations_on_user_id                 (user_id)
#  index_recommendations_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  fk_rails_...  (place_id => places.id)
#  fk_rails_...  (user_id => users.id)
#
class Recommendation < ApplicationRecord
  belongs_to :user, validate: true
  belongs_to :place, validate: true
  has_many :guide_recommendations, dependent: :destroy
  has_many :guides, through: :guide_recommendations

  validates :user_id, presence: true
  validates :title, presence: true
  validates :content, presence: true

  default_scope -> { order(created_at: :desc) }
end

app/controllers/recommendations_controller.rb
# frozen_string_literal: true

# Resource controller for recommendations
class RecommendationsController < ApplicationController
  before_action :logged_in_user, only: %i[create update destroy]
  before_action :set_recommendation, only: %i[show edit update destroy]

  # GET /recommendations/1
  def show; end

  # GET /recommendations/1/edit
  def edit
    @place = @recommendation.place
  end

  # POST /recommendations
  def create
    @recommendation = current_user.recommendations.build(recommendation_params)

    if @recommendation.save
      redirect_to current_user, notice: 'Recommendation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /recommendations/new
  def new
    @place = Place.exists?(id: params[:place]) ? Place.find(params[:place]) : Place.new
    @recommendation = Recommendation.new
  end

  # PATCH/PUT /recommendations/1
  def update
    if @recommendation.update(recommendation_params)
      redirect_to current_user, notice: 'Recommendation was successfully updated.'
    else
      render current_user
    end
  end

  # DELETE /recommendations/1
  def destroy
    @recommendation.destroy
    redirect_to current_user, notice: 'Recommendation was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recommendation
    @recommendation = Recommendation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recommendation_params
    params.require(:recommendation).permit(:content, :title, :place_id)
  end
end

app/views/recommendations/_form.html.erb
<%= form_with(model: @recommendation, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field w-full">
    <%= f.hidden_field :place_id, value: @place.id %>

    <%= f.label :place_id %>
    <% if @place.id %>
      <%= render 'places/place', place: @place, class_name: 'mb-4' %>
    <% else %>
      <%= f.collection_select :place_id, Place.all, :id, :name, { prompt: 'Select or search a place', disabled: "", selected: "" }, 'data-controller': 'datalist' %>
    <% end %>

    <%= f.label :title %>
    <%= f.text_field :title, class: "w-full mb-4" %>

    <%= f.label :content, "Description" %>
    <%= f.text_area :content, class: "w-full" %>
  </div>

  <%= f.submit "Create recommendation", class: "btn btn-primary mt-5" %>
<% end %>

app/views/recommendations/_recommendation.html.erb
<li class="rounded-lg flex flex-col justify-between shadow-lg p-8">
  <div>
    <div class="flex justify-between items-start flex-wrap-reverse md:flex-nowrap">
      <a href="<%= recommendation_path recommendation %>"><h2 class="font-bold text-xl"><%= recommendation.title %></h2></a>
      <% if local_assigns[:destination] %>
        <a class="flex gap-1 items-center" href="<%= place_path recommendation.place %>">
          <p class="w-max"><%= recommendation.place&.name %></p>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
          </svg>
        </a>
      <% end %>
    </div>
    <div class="mt-2 line-clamp-3"><%= recommendation.content %></div>
  </div>
  <a class="border-cerulean-500 mt-4 -ml-2 rounded-md py-1 px-2 w-max text-cerulean-500 border-2 text-sm items-center font-bold flex justify-between" href="<%= recommendation_path recommendation %>">
    More info
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6" />
    </svg>
  </a>
  <% if local_assigns[:user] && user %>
    <a href="<%= user_path recommendation.user %>" class="flex gap-2 mt-5">
      <%= gravatar_for recommendation.user, size: 28 %>
      <p><%= recommendation.user.name %></p>
    </a>
  <% end %>
</li>

app/views/recommendations/edit.html.erb
<% provide(:title, 'Edit Recommendation') %>
<%= render 'shared/main' do %>
  <%= render 'shared/main_heading', classes: 'text-center' do %>
    Edit Recommendation
  <% end %>

  <div class="sm:max-w-2xl mt-10 mx-auto">
    <%= render 'form', recommendation: @recommendation %>
  </div>
<% end %>

app/views/recommendations/new.html.erb
<% provide(:title, 'New Recommendation') %>
<%= render 'shared/main' do %>
  <%= render 'shared/main_heading', classes: 'text-center' do %>
    Create a Recommendation
  <% end %>

  <div class="sm:max-w-2xl mt-10 mx-auto">
    <%= render 'form', recommendation: @recommendation %>
  </div>
<% end %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>