config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',            to: 'static_pages#about'
  get    '/signup',           to: 'users#new'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'
  get    '/users/:id/guides', to: 'users#guides'
  get    '/users/:id/recommendations',
                              to: 'users#recommendations'
  resources :destinations, only: %i[index show]
  resources :recommendations
  resources :users
  resources :guides, only: %i[new create show]
  resources :places, only: %i[show]
  resources :account_activations, only: %i[create edit]
  resources :password_resets, only: %i[new create edit update]
  resources :recommendations, except: %i[index]
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                :bigint           not null, primary key
#  activated         :boolean          default(FALSE)
#  activated_at      :datetime
#  activation_digest :string
#  admin             :boolean          default(FALSE)
#  email             :string
#  name              :string
#  password_digest   :string
#  remember_digest   :string
#  reset_digest      :string
#  reset_sent_at     :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  has_many :recommendations, dependent: :destroy
  has_many :guides, dependent: :destroy

  attr_accessor :remember_token, :activation_token, :reset_token

  before_save   :downcase_email
  before_create :create_activation_digest

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  scope :activated, -> { User.where(activated: true) }

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    # rubocop:disable Rails/SkipsModelValidations
    update_attribute(:remember_digest, User.digest(remember_token))
    # rubocop:enable Rails/SkipsModelValidations
    remember_digest
  end

  # Returns a session token to prevent session hijacking.
  # We reuse the remember digest for convenience.
  def session_token
    remember_digest || remember
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    # rubocop:disable Rails/SkipsModelValidations
    update_attribute(:remember_digest, nil)
    # rubocop:enable Rails/SkipsModelValidations
  end

  # Activates an account.
  def activate
    # rubocop:disable Rails/SkipsModelValidations
    update_columns(activated: true, activated_at: Time.zone.now)
    # rubocop:enable Rails/SkipsModelValidations
  end

  # Sends activation email.
  def send_activation_email
    unless activation_token
      create_activation_digest
      save!
    end
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    # rubocop:disable Rails/SkipsModelValidations
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
    # rubocop:enable Rails/SkipsModelValidations
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Expires a reset token so it can't be reused
  def expire_reset_token
    # rubocop:disable Rails/SkipsModelValidations
    update_attribute(:reset_digest, nil)
    # rubocop:enable Rails/SkipsModelValidations
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Resource controller for Users
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update show destroy]
  before_action :activated_user, only: %i[index destroy]
  before_action :correct_user,   only: %i[edit update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @recommendations = @user.recommendations.limit(5)
    @guides = @user.guides.limit(5)
    activated_user unless current_user?(@user) || current_user.activated?
    redirect_to root_url unless @user.activated? || current_user?(@user)
  end

  def guides
    @user = User.find(params[:id])
    @guides = @user.guides.paginate(page: params[:page], per_page: 33)
  end

  def recommendations
    @user = User.find(params[:id])
    @recommendations = @user.recommendations.paginate(page: params[:page], per_page: 33)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) # Not the final implementation!
    if @user.save
      reset_session
      log_in @user
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Settings saved.'
      redirect_to edit_user_path @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Helper methods for users
module UsersHelper
  def gravatar_for(user, size: 200, class_name: '')
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar rounded-full #{class_name}")
  end
end

app/views/users/_user.html.erb
<li class="transition-transform shadow-lg hover:shadow-2xl hover:-translate-y-1 dark:bg-gray-900 dark:hover:bg-gray-800 border-2 rounded-lg border-gray-500 ">
  <%= link_to user, class: "p-5 flex flex-col justify-center items-center" do %>
    <div class="rounded-full overflow-hidden w-32 mb-4">
      <%= gravatar_for user %>
    </div>
    <h2 class="font-bold text-lg"><%= user.name %></h2>
  <% end %>

  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure you want to delete the user #{user.name}?" }, class: "mb-5 mx-5 btn btn-secondary btn-sm block text-center" %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Settings') %>
<%= render 'shared/main' do %>
  <%= render 'shared/main_heading', classes: 'text-center' do %>
    Settings
  <% end %>

  <div class="sm:max-w-sm mt-10 mx-auto">
    <% if !@user.activated? %>
      <%= render 'shared/banner', locals: {message_type: :info} do %>
        <div>Your account is not activated. Check your email for an activation link to gain full access to Destination.</div>
        <%= link_to 'Resend activation email', account_activations_path, method: :post, class: 'block underline font-semibold mt-2' %>
      <% end %>
    <% end %>

    <div class="text-center">
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener" class="inline-block mt-2">
        <div class="rounded-full overflow-hidden w-24 mx-auto relative">
          <%= gravatar_for @user %>
          <div class="opacity-0 absolute top-0 w-full h-full hover:opacity-90 transition">
            <div class="absolute bottom-0 left-0 right-0 py-2 text-white bg-gray-800 text-sm font-semibold">
              Update
            </div>
          </div>
        </div>
      </a>
    </div>

    <%= render 'shared/user_form', button_label: 'Save' %>
  </div>
<% end %>

app/views/users/guides.html.erb
<% provide :title, "Guides - #{@user.name}" %>

<%= render 'shared/main' do %>
  <%= render 'shared/main_heading' do %>
    Guides - <%= @user.name %>
  <% end %>
  <a class="flex gap-2 items-center my-6 ml-4 font-bold" href="<%= user_path @user %>">
    <%= gravatar_for @user, size: 32 %>
    <p><%= @user.name %></p>
  </a>
  <% if @guides.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 my-6">
      <% @guides.each do |guide| %>
        <%= render guide, extra: true, no_user: true, destination: true %>
      <% end %>
    </div>
    <%= will_paginate @guides %>
  <% else %>
    <p class="font-bold text-lg mt-6">No guides available.</p>
  <% end %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "All users") %>

<%= render 'shared/main' do %>
  <%= render 'shared/main_heading' do %>
    All users
  <% end %>

  <div class="mt-10">
    <%= will_paginate %>
  </div>

  <ul class="mt-10 grid grid-cols-4 grid-flow-row gap-4">
    <%= render @users %>
  </ul>

  <div class="mt-10">
    <%= will_paginate %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<%= render 'shared/main' do %>
  <%= render 'shared/main_heading', classes: 'text-center' do %>
    Sign up
  <% end %>

  <div class="sm:max-w-sm mt-10 mx-auto">
      <%= render 'shared/user_form' %>
      <p class="mt-5 text-center">
        Already have an account? <%= link_to "Log in.", login_path, class: "underline" %>
      </p>
  </div>
<% end %>

app/views/users/recommendations.html.erb
<% provide :title, "Recommendations - #{@user.name}" %>

<%= render 'shared/main' do %>
  <%= render 'shared/main_heading' do %>
    Recommendations - <%= @user.name %>
  <% end %>
  <a class="flex gap-2 items-center my-6 ml-4 font-bold" href="<%= user_path @user %>">
    <%= gravatar_for @user, size: 32 %>
    <p><%= @user.name %></p>
  </a>
  <% if @recommendations.any? %>
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 my-6">
      <%= render @recommendations, destination: true %>
    </div>
    <%= will_paginate @recommendations %>
  <% else %>
    <p class="font-bold text-lg mt-6">No guides available.</p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="max-w-7xl mx-auto flex flex-wrap lg:flex-nowrap justify-center items-start">
  <%= render 'layouts/sidebar' do %>
    <div class="flex flex-col">
      <div class="rounded-full overflow-hidden w-full mr-4">
        <%= gravatar_for @user, size: 400%>
      </div>

      <div class="mt-5">
        <h1 class="font-bold text-2xl"><%= @user.name %></h1>
        <div><%= @user.email %></div>
        <% if current_user == @user %>
          <a class="block btn btn-default btn-sm mt-5" href="<%= edit_user_path current_user %>">Edit profile</a>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="pt-5 w-full px-4 sm:pt-6 sm:px-6 md:pt-8 lg:pt-10 lg:px-8 xl:pt-15">
    <div class="mb-12" id="guides">
      <h2 class="text-4xl text-center lg:text-left font-bold mb-5">
        <% if @user == current_user %>
          Your guides
        <% else %>
          Guides for <%= @user.name %>
        <% end %>
      </h2>

      <% if @guides.any? %>
        <ol class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <% @guides.each do |guide| %>
            <%= render guide, extra: true, no_user: true, destination: true %>
          <% end %>
          <div class="text-center flex flex-col justify-center items-center font-bold text-xl">
            <a href="/users/<%= @user.id %>/guides" class="hover:underline my-5">
              View all
            </a>
          </div>
        </ol>
      <% else %>
        <p class="mb-6 text-lg ml-4">No guides available.</p>
      <% end %>
    </div>
    <div id="recommendations">
      <h2 class="text-4xl text-center lg:text-left font-bold mb-5">
        <% if @user == current_user %>
          Your recommendations
        <% else %>
          Recommendations for <%= @user.name %>
        <% end %>
      </h2>

      <% if @recommendations.any? %>
        <ol class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <% @recommendations.each do |recommendation| %>
            <%= render recommendation, destination: true %>
          <% end %>
          <div class="text-center flex flex-col justify-center font-bold text-xl">
            <a href="/users/<%= @user.id %>/recommendations" class="hover:underline my-5">
              View all
            </a>
          </div>
        </ol>
      <% else %>
        <p class="text-lg ml-4">No recommendations available.</p>
      <% end %>
    </div>
  </div>
</div>