config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',            to: 'static_pages#about'
  get    '/signup',           to: 'users#new'
  get    '/login',            to: 'sessions#new'
  post   '/login',            to: 'sessions#create'
  delete '/logout',           to: 'sessions#destroy'
  get    '/users/:id/guides', to: 'users#guides'
  get    '/users/:id/recommendations',
                              to: 'users#recommendations'
  resources :destinations, only: %i[index show]
  resources :recommendations
  resources :users
  resources :guides, only: %i[new create show]
  resources :places, only: %i[show]
  resources :account_activations, only: %i[create edit]
  resources :password_resets, only: %i[new create edit update]
  resources :recommendations, except: %i[index]
end

app/views/layouts/_footer.html.erb
<footer class="py-4 mt-10 text-gray-500 text-sm">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <hr class="mb-5 dark:border-gray-500" />
    <nav>
      <ul class="flex items-center justify-center">
        <li><%= link_to "About",   about_path,  class: "px-2 hover:underline" %></li>
      </ul>
    </nav>

    <small class="block text-center mt-5">
      Copyright ©<%= Date.today.year %> Eric Cecchi. All rights reserved.
    </small>

    <%#= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="dark:bg-gray-900" data-controller="dropdown">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex-1 flex items-center sm:items-stretch justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to "Destination", root_path, class: "font-bold text-lg text-gray-900 dark:text-white" %>
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= link_to "Home", root_path, class: "text-gray-600 focus:bg-gray-100 hover:bg-gray-100 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Destinations", destinations_path, class: "text-gray-600  focus:bg-gray-100 hover:bg-gray-100 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% if logged_in? %>
              <%= link_to "Users", users_path, class: "text-gray-600 focus:bg-gray-100 hover:bg-gray-100 hover:text-gray-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button data-action="click->dropdown#toggle" data-dropdown-target="button" type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-800 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Heroicon name: outline/menu-alt-2

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="hidden sm:block flex items-center sm:ml-6">
        <% if logged_in? %>
          <div class="relative inline-block text-left" data-controller="dropdown">
            <div>
              <button type="button" class="transition px-3 py-2 inline-flex rounded-md items-center justify-center w-full text-sm font-medium text-gray-800 focus:outline-none focus:bg-gray-100 hover:bg-gray-100" id="menu-button" aria-expanded="false" aria-haspopup="true" data-action="click->dropdown#toggle" data-dropdown-target="button">
                <div class="hidden sm:block">
                  <%= current_user.name %>
                </div>

                <div class="rounded-full overflow-hidden w-7 sm:ml-4">
                  <%= gravatar_for current_user, size: 100 %>
                </div>
              </button>
            </div>

            <div data-dropdown-target="menu" class="origin-top-right absolute z-30 right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none divide-y divide-gray-100 hidden" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
              <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
              <div class="py-1" role="none">
                <%= link_to "Profile", current_user, class: "transition text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
                <%= link_to "Settings", edit_user_path(current_user), class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
              </div>
              <div class="py-1" role="none">
                <%= link_to "Log out", logout_path, method: :delete, class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100", role: "menuitem", tabindex: "-1" %>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to "Log in", login_path, class: "btn btn-sm btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div data-dropdown-target="menu" class="hidden sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <%= link_to "Home", root_path, class: "text-gray-900 block px-3 py-2 rounded-md text-base font-medium" %>
      <%= link_to "Destinations", destinations_path, class: "text-gray-500 block hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
      <% if logged_in? %>
        <%= link_to "Profile", current_user, class: "text-gray-500 block hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        <%= link_to "Settings", edit_user_path(current_user), class: "text-gray-500 block hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
        <%= link_to "Log out", logout_path, method: :delete, class: "text-gray-500 block hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "text-gray-500 block hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="pt-5 max-w-xs px-4 sm:pt-6 sm:px-6 md:pt-8 lg:pt-10 lg:px-8 xl:pt-15">
  <%= yield %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-200 relative">
  <%= render 'layouts/header' %>
  <% unless flash.empty? %>
    <div id="flash-container" class="max-w-7xl mx-auto">
      <% flash.each do |message_type, message| %>
        <%= render 'shared/banner', message_type: message_type do %>
          <%= message %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>